language: php

php:
  - 7.4

os:
  linux

dist:
  xenial

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install --no-progress --prefer-dist

script:
  - make cs

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
